### ISSUE TITLE
Has anyone used Swashbuckle.Examples with Swashbuckle.OData ?

### ISSUE THREAD

**Issue by bkwdesign** [mattfrear/Swashbuckle.Examples#4]
My OData controller has a PATCH operation that takes a custom parameter I use for parsing the object delta information that the web client submits.

My operation's signature is kinda like..
```
[AcceptVerbs("PATCH", "MERGE")]
[SwaggerRequestExample(typeof(MyCorp.OData.Delta<BizEntity>,typeof(OdataDeltaExample))] 
public IHttpActionResult Patch([FromODataUri] long key, MyCorp.OData.Delta<BizEntity> patchBizEntity)
```
Would love my swagger UI to show an example of this...
I've decorated my operation w/the appropriate SwaggerRequestExample attribute...

Getting a null ref exception..

```
   at Swashbuckle.Examples.ExamplesOperationFilter.SetRequestModelExamples(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
   at Swashbuckle.Examples.ExamplesOperationFilter.Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
   at Swashbuckle.OData.ODataSwaggerProvider.CreateOperation(ApiDescription apiDescription, SchemaRegistry schemaRegistry) in C:\Users\rbeauchamp\Documents\GitHub\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 228
   at Swashbuckle.OData.ODataSwaggerProvider.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry) in C:\Users\rbeauchamp\Documents\GitHub\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 177
   at Swashbuckle.OData.ODataSwaggerProvider.<>c__DisplayClass5_0.<GenerateSwagger>b__3(IGrouping`2 group) in C:\Users\rbeauchamp\Documents\GitHub\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 83
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.OData.ODataSwaggerProvider.GenerateSwagger(String rootUrl, String apiVersion) in C:\Users\rbeauchamp\Documents\GitHub\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 79
   at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion) in C:\Users\rbeauchamp\Documents\GitHub\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 56
   at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()
```

**Comment by TrevorVonSeggern** [comment]
Try:
[SwaggerRequestExample(typeof(BizEntity, typeof(OdataDeltaExample))]

**Comment by mattfrear** [comment]
@bkwdesign the NullReferenceException was fixed on 8th of August. If you remove the `[SwaggerRequestExample]` attribute, do you see anything in the request example area, or is it empty like this:
![image](https://user-images.githubusercontent.com/169179/29999023-59d292fa-9031-11e7-8696-7d23ecf743f6.png)

**Comment by mattfrear** [comment]
Closing due to no feedback
